# Change these first
owner: arian24b # Your GitHub organization or username, where this repository lives
repo: utm # The name of this repository

sites:
  - name: devdon.ir
    url: https://devdon.ir
  - name: arianomrani.ir
    url: https://arianomrani.ir
  - name: v
    url: https://v.udns.site
  - name: cp
    url: https://cp.udns.site
  - name: arianameson.ir
    url: https://arianameson.ir
  - name: soha
    url: soha.udns.site
    port: 53
    check: "tcp-ping"
  - name: aida
    url: aida.udns.site
    port: 53
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: utm.udns.site
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UDNS Uptime Monitoring
  introTitle: "**UDNS Uptime Monitoring** is monitoring my server."
  introMessage: This is a monitoring status page which uses **real-time** data from my [GitHub repository](https://github.com/arian24b). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: My GitHub
      href: https://github.com/$OWNER/$REPO
    - title: My Site
      href: https://devdon.ir
  theme: dark
  robotsText: "User-agent: * \n Disallow: /"
  footer: This page is [open source]($REPO), [DevDon](https://devdon.ir)] 
