owner: arian24b
repo: utm

sites:
  - name: devdon.ir
    url: https://devdon.ir
  - name: arianomrani.ir
    url: https://arianomrani.ir
  - name: v
    url: https://v.udns.site
  - name: msn
    url: https://msn.udns.site
  - name: cp
    url: https://cp.udns.site
  - name: arianameson.ir
    url: https://arianameson.ir
  - name: v.cloud-game.site
    url: https://v.cloud-game.site
  - name: soha
    url: soha.udns.site
    port: $SSH_PORT
    check: "tcp-ping"
  - name: aida
    url: aida.udns.site
    port: $SSH_PORT
    check: "tcp-ping"
  - name: servern2
    url: servern2.udns.site
    port: $SSH_PORT
    check: "tcp-ping"
  - name: servern4
    url: servern4.udns.site
    port: $SSH_PORT
    check: "tcp-ping"
  - name: servern4
    url: servern4.udns.site
    port: $SSH_PORT
    check: "tcp-ping"
  - name: kane
    url: kane.cloud-game.site
    port: $SSH_PORT
    check: "tcp-ping"
  - name: servern4
    url: milly.cloud-game.site
    port: $SSH_PORT
    check: "tcp-ping"

status-website:
  cname: utm.udns.site
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UDNS UTM
  introTitle: "**UDNS UTM** monitoring my server. :))"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: My GitHub
      href: https://github.com/$OWNER
    - title: My Site
      href: https://devdon.ir
  theme: night
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: "[devdon](https://devdon.ir)"
