# Repository
owner: arian24b
repo: utm

# Endpoints
sites:
  - name: insightsite.info
    url: https://insightsite.info
    delay: 2000
  - name: demo.insightsite.info
    url: https://demo.insightsite.info
    delay: 2000
  - name: insightsite.ir
    url: https://insightsite.ir
    delay: 2000
  - name: devdon.ir
    url: https://devdon.ir
    delay: 2000
  - name: arianomrani.ir
    url: https://arianomrani.ir
    delay: 2000
  - name: v.usite.tech
    url: https://v.usite.tech
    delay: 2000
  - name: cp.usite.tech
    url: https://cp.usite.tech
    delay: 2000
  - name: arianameson.ir
    url: https://arianameson.ir
    delay: 2000
  - name: s2dio.ir
    url: https://s2dio.ir
    delay: 2000
  - name: ablmoasherati.ir
    url: https://ablmoasherati.ir
    delay: 2000
  - name: calendarix.pro
    url: https://calendarix.pro
    delay: 2000
  - name: api.calendarix.pro
    url: https://api.calendarix.pro
    delay: 2000
  - name: utm.usite.tech
    url: https://utm.usite.tech
    delay: 2000
  - name: soha
    url: soha.usite.tech
    port: $SSH_PORT
    check: "tcp-ping"
    delay: 2000
  - name: mahsa
    url: mahsa.usite.tech
    port: $SSH_PORT
    check: "tcp-ping"
    delay: 2000
  - name: ariandev.ir
    url: https://ariandev.ir
    delay: 2000
  - name: dl.devdon.ir
    url: https://dl.devdon.ir
    delay: 2000
  - name: s.usite.tech
    url: https://s.usite.tech
    port: 2096
    check: "tcp-ping"
    delay: 2000
  - name: n8n.usite.tech
    url: https://n8n.usite.tech
    delay: 2000
  - name: portainer.usite.tech
    url: https://portainer.usite.tech
    delay: 2000

status-website:
  cname: utm.usite.tech
  logoUrl: https://dl.devdon.ir/images/favicon.ico
  name: UDNS UTM
  introTitle: "**UDNS UTM** monitoring my server. :))"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: My GitHub
      href: https://github.com/$OWNER
    - title: My Site and Blog
      href: https://s2dio.ir
  theme: night
  robotsText: "User-agent: * \n Disallow: /"
  favicon: https://dl.devdon.ir/images/favicon.ico
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
i18n:
  footer: "[S2DIO](https://s2dio.ir)"
