owner: arian24b
repo: utm

sites:
  - name: devdon.ir
    url: https://devdon.ir
  - name: arianomrani.ir
    url: https://arianomrani.ir
  - name: v
    url: https://v.udns.site
  - name: cp
    url: https://cp.udns.site
  - name: arianameson.ir
    url: https://arianameson.ir
  - name: soha
    url: soha.udns.site
    port: $SSH_PORT
    check: "tcp-ping"
  - name: aida
    url: aida.udns.site
    port: $SSH_PORT
    check: "tcp-ping"

status-website:
  cname: utm.udns.site
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UDNS Uptime Monitoring
  introTitle: "**UDNS Uptime Monitoring** is monitoring my server."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: My GitHub
      href: https://github.com/$OWNER/$REPO
    - title: My Site
      href: https://devdon.ir
  theme: dark
  robotsText: "User-agent: * \n Disallow: /"
  footer: This page is [open source]($REPO), [DevDon](https://devdon.ir)] 
