# Repository
owner: arian24b
repo: utm

# Endpoints
sites:
  - name: devdon.ir
    url: https://devdon.ir
    delay: 2000
  - name: arianomrani.ir
    url: https://arianomrani.ir
    delay: 2000
  - name: v.udns.site
    url: https://v.udns.site
    delay: 2000
  - name: msn.udns.site
    url: https://msn.udns.site
    delay: 2000
  - name: cp.udns.site
    url: https://cp.udns.site
    delay: 2000
  - name: arianameson.ir
    url: https://arianameson.ir
    delay: 2000
  - name: utm.udns.site
    url: https://utm.udns.site
    delay: 2000
  - name: soha
    url: soha.udns.site
    port: $SSH_PORT
    check: "tcp-ping"
    delay: 2000
  - name: shima
    url: shima.udns.site
    port: $SSH_PORT
    check: "tcp-ping"
    delay: 2000
  - name: servern2
    url: servern2.udns.site
    port: $SSH_PORT
    check: "tcp-ping"
    delay: 2000

status-website:
  cname: utm.udns.site
  logoUrl: https://devdon.ir/wp-content/uploads/2024/08/devdon.png
  name: UDNS UTM
  introTitle: "**UDNS UTM** monitoring my server. :))"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: My GitHub
      href: https://github.com/$OWNER
    - title: My Site and Blog
      href: https://devdon.ir
  theme: night
  robotsText: "User-agent: * \n Disallow: /"
  favicon: https://devdon.ir/wp-content/uploads/2024/08/devdon.png
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"

i18n:
  footer: "[devdon](https://devdon.ir)"
